# Vaihe 1: build vaihe
FROM node:20-alpine AS build

RUN echo "Buildataan paikalliseen ympäristöön tarkoitetulla Dockerfilella"

WORKDIR /app

COPY package*.json ./

# Asenna riippuvuudet
RUN npm install

COPY . .

RUN npm run build


# Vaihe 2: tuotantovaihe
FROM nginxinc/nginx-unprivileged:alpine
COPY --from=build /app/dist /usr/share/nginx/html


EXPOSE 8080

# Käynnistä nginx palvelin, siten, että se pysyy etualalla
CMD ["nginx", "-g", "daemon off;"]