services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - node_modules:/app/node_modules
    container_name: frontend_c
    ports:
      - '8080:8080'
  backend:
    build: ./server
    container_name: backend_c
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
  


# Määritä nimetty volyymi täällä
volumes:
  node_modules: