version: "3.8"
services:
  frontend:
    build:
      context: ./client
      args:
        VITE_API_URL: http://backend:3000
    links:
      - backend
    container_name: frontend_c
    ports:
      - '8080:8080'
  backend:
    build: ./server
    container_name: backend_c
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
