GET http://localhost:3003/api/trips
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjkyODg2OGRjNDRlYTZhOThjODhiMzkzZDM2NDQ1MTM2NWViYjMwZDgiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYmlrZXNhZmUtNGQyNTYiLCJhdWQiOiJiaWtlc2FmZS00ZDI1NiIsImF1dGhfdGltZSI6MTczMjAwMDg0MywidXNlcl9pZCI6ImI0bUNia1hBRWlkZUkyODQxRllWZk9VNnRBWjIiLCJzdWIiOiJiNG1DYmtYQUVpZGVJMjg0MUZZVmZPVTZ0QVoyIiwiaWF0IjoxNzMyMDAxOTEyLCJleHAiOjE3MzIwMDU1MTIsImVtYWlsIjoidGVzdGltaWVzQHRlc3RhYWphLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ0ZXN0aW1pZXNAdGVzdGFhamEuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.DH4T_SRC1ApSf3BLAohqMEltjXWew4yamkghtIolwzvcI3nKxxlfaLQ2wsX4PcIWRqCKzzBOjDxNDMpkBFZ7lVZKlwzYc8OxWL_MIVu8cLPKtDXHbg4OFHfcc98Xyn5vu7gDNAR_2nLhVsrKVoTERwRee1sGBeQJNl3BTkzLJ3rnO1lXCIsxJCpXX72BggABqh2kMH4L19N0B5OHL8dQPEoiFz8gKVgcwkJ39BmNGef_dPLM-XKSIZ3PONt9QUM1_6Q0va0XszWMk8kMFabBXMGl495u59OQShuyY9RDO_PzLLojFWTbzs3MbvLdeqXXhlhugD_zM3i26-4xuLO6uQ