name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [staging]
    types: [opened, synchronize]
    

jobs:
    pipeline_server:
        runs-on: ubuntu-latest
        services:
          postgres:
            image: postgres
            env:
              POSTGRES_DB: postgres
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: postgres
            ports:
               - 5432:5432
            options: >-
              --health-cmd pg_isready
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5
        defaults:
            run:
                working-directory: ./server
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: '20'
            - name: Install dependencies
              run: npm install
            - name: Check style
              run: npm run lint
            - name: Test
              env:
                TEST_DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
              run: npm run test
              
    pipeline_client:
      runs-on: ubuntu-latest
      defaults:
          run:
              working-directory: ./client
      steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-node@v4
            with:
              node-version: '20'
          - name: Install dependencies
            run: npm install
          - name: Check style
            run: npm run lint
          - name: Test
            run: npm run test
          - name: Run docker-compose
            uses: hoverkraft-tech/compose-action@v2.0.2
            with:
              compose-file: "./docker-compose.yaml"
          - name: e2e tests
            uses: cypress-io/github-action@v6
            working-directory: ./client
            with:
              command: npm run cypress:test